#!/usr/bin/env bash

cmd=$1

case "$cmd" in
"install")
    go get -u \
        golang.org/x/tools/cmd/goimports \
        golang.org/x/lint/golint \
        honnef.co/go/tools/cmd/megacheck \
        mvdan.cc/interfacer \
        github.com/alexkohler/prealloc \
        github.com/kisielk/errcheck
    ;;

"coverage")
    OUT=/tmp/cover.out && go test ./... -coverprofile $OUT && go tool cover -html=$OUT
    ;;

"test")
    go test ./...
    ;;

*)
    tools=(
        "go fmt ./..."
        "goimports . > /dev/null"
        "go vet ./..."
        "go test ./..."
        "golint ./..."
        "megacheck ./..."
        "interfacer ./..."
        "prealloc ./..."
        "errcheck ./..."
    )
    for var in "${tools[@]}"
    do
      echo "${var}"
      sh -c "${var}"
      echo
    done
    ;;
esac
