#!/usr/bin/env bash

cmd=$1

base="github.com/andreiavrammsd/apixu-go"
pkg=". ${base}/formatter ${base}/response ${base}/types"

case "${cmd}" in
"install")
    go get -u \
        golang.org/x/tools/cmd/goimports \
        golang.org/x/lint/golint \
        honnef.co/go/tools/cmd/megacheck \
        mvdan.cc/interfacer \
        github.com/alexkohler/prealloc \
        github.com/kisielk/errcheck
    ;;

"coverage")
    OUT=/tmp/cover.out && go test ${pkg} -coverprofile ${OUT} && go tool cover -html=${OUT}
    ;;

"test")
    go test ${pkg}
    ;;

*)
    tools=(
        "go fmt ${pkg}"
        "go vet ${pkg}"
        "go test ${pkg}"
        "golint ./..."
        "megacheck ${pkg}"
        "interfacer ${pkg}"
        "prealloc ${pkg}"
        "errcheck ${pkg}"
    )
    for var in "${tools[@]}"
    do
      echo "${var}"
      sh -c "${var}"
      echo
    done
    ;;
esac
